name: PR Test Risk Profiler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-risk-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install PyGithub lizard pyyaml

      - name: Run PR Risk Profiler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          python tools/pr_risk_profiler.py